apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: v0.15.2
    releaseName: metallb
    namespace: metallb
