apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            chartPath: apps/cert-manager/overlays/dev
            wave: "0"
          # - name: istiod
          #   namespace: istiod
          #   chartPath: apps/istiod/overlays/dev
          #   wave: "1"
          - name: kargo
            namespace: kargo
            chartPath: apps/kargo/overlays/dev
            wave: "1"
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/valkiriaaquatica/argocd-kustomize-environments.git
        targetRevision: test/sync-waves
        path: '{{chartPath}}'
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy: 
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true