api:
  enabled: false
  adminAccount:
    password: admin
    tokenSigningKey: iwishtowashmyirishwristwatch
  argocd:
    urls: 
      shard-one: http://argocd-server.argocd.svc.cluster.local 


controller:
  shardName: shard-one
  globalCredentials:
    namespaces:
      - kargo

kubeconfigSecrets:
  kargo: kargo-controlplane-kubeconfig

managementController:
  enabled: false
garbageCollector:
  enabled: false