apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications-second-deploy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - name: kargo
            namespace: kargo
            chartPath: apps/kargo/overlays/sharded-main
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/valkiriaaquatica/argocd-kustomize-environments.git
        targetRevision: test/kargo-sharded-rollouts
        path: '{{chartPath}}'
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true