apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications-zero-deploy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  generators:
    - list:
        elements:
          - name: external-secrets
            namespace: external-secrets
            chartPath: apps/external-secrets/overlays/dev
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/valkiriaaquatica/argocd-kustomize-environments.git
        targetRevision: test/app-of-apps-and-syncwaves
        path: '{{chartPath}}'
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true