apiVersion: v1
kind: Service
metadata:
  name: canary-demo-preview
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: rollouts-test
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo
---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: rollouts-test
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo