apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.16.0
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
    valuesMerge: merge 
