apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: v0.18.2
    releaseName: external-secrets
    namespace: external-secrets
