
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/valkiriaaquatica/argocd-kustomize-environments.git
    targetRevision: test/app-of-apps-and-syncwaves
    path: applicationsets/dev-app/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true