---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - applicationset/zero-deploy.yaml
  # - applicationset/first-deploy.yaml
  # - applicationset/second-deploy.yaml
  - applicationset/third-deploy.yaml
